analytics/urls.py
#This contains url patterns to be recognised by the url requested from the browser and to call the corresponding view.

from django.conf.urls import url
from . import views


app_name = 'analytics'

urlpatterns = [

    #/analytics/
    url(r'^$', views.main, name = 'main'),

    #/analytics/mycommute/
    url(r'^mycommute/$', views.MycommuteView.as_view(), name = 'mycommute'),

    #/analytics/mycommute/process_gpsdata/
    url(r'^mycommute/process_gpsdata/$', views.process_gpsdata, name = 'process_gpsdata'),

    #/analytics/json_data/
    url(r'^json_data/$', views.json_data, name ='json_data'),

    #/analytics/register/
    url(r'^register/$', views.user_register, name='register'),

    #/analytics/login_user/
    url(r'^login_user/$', views.login_user, name='login_user'),

    #/analytics/logout_user/
    url(r'^logout_user/$', views.logout_user, name='logout_user'),



]

cyclist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^analytics/', include('analytics.urls')),
]

if settings.DEBUG: # whenever on developer mode, use the directory defined in settings
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analytics/models.py
# -*- coding: utf-8 -*-
#This contains models to map their corresponding tables of the database
#The models for OpenStreetMap network data which are mounted in the database were generated by Django "inspectdb" command
#inspectdb create models by introspecting an existing database.

from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.auth.models import User

from django.contrib.postgres.fields import JSONField

#zipgpx table
class ZIPGPX(models.Model):
    user = models.ForeignKey(User, default=1)
    filename = models.FileField()

#gpxfile table
class GPXFile(models.Model):
    user = models.ForeignKey(User, default=1)
    filename = models.FileField()
    segments = models.TextField(null=True)

#gpxpoint table
class GPXPoint(models.Model):
    user = models.ForeignKey(User, default=1)
    gpxfile = models.ForeignKey(GPXFile, default=1)
    point = models.PointField(srid=4326)
    timestamp = models.DateTimeField()
    objects = models.GeoManager()

    def __unicode__(self):
        return unicode(self.gpxfile)

#segmentgeojson table
class SegmentGeoJSON(models.Model):
    user = models.ForeignKey(User, default=1)
    gpxfile = models.ForeignKey(GPXFile, default=1)
    geojson = JSONField()

#segmentcounts table
class SegmentCounts(models.Model):
    user = models.ForeignKey(User, default=1)
    segment_id = models.IntegerField()
    segment_counts = models.IntegerField()

#route table
class Route(models.Model):
    user = models.ForeignKey(User, default=1)
    route_id = models.IntegerField()
    route_counts = models.IntegerField()
    route_color = models.TextField()
    route_tt = models.IntegerField()

#matchingpoint table
class MatchingPoint(models.Model):
    user = models.ForeignKey(User, default=1)
    gpxfile = models.ForeignKey(GPXFile, default=1)
    point = models.PointField(srid=4326)
    objects = models.GeoManager()

# The followings are models for OpenStreetMap network data table
class OsmWayTypes(models.Model):
    type_id = models.IntegerField(primary_key=True)
    name = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'osm_way_types'

class OsmWayClasses(models.Model):
    class_id = models.IntegerField(primary_key=True)
    type = models.ForeignKey(OsmWayTypes, models.DO_NOTHING, blank=True, null=True)
    name = models.TextField(blank=True, null=True)
    priority = models.FloatField(blank=True, null=True)
    default_maxspeed = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'osm_way_classes'

class Ways(models.Model):
    gid = models.BigAutoField(primary_key=True)
    class_field = models.ForeignKey(OsmWayClasses, models.DO_NOTHING, db_column='class_id')
    # Field renamed because it was a Python reserved word.
    length = models.FloatField(blank=True, null=True)
    length_m = models.FloatField(blank=True, null=True)
    name = models.TextField(blank=True, null=True)
    x1 = models.FloatField(blank=True, null=True)
    y1 = models.FloatField(blank=True, null=True)
    x2 = models.FloatField(blank=True, null=True)
    y2 = models.FloatField(blank=True, null=True)
    osm_id = models.BigIntegerField(blank=True, null=True)
    source_osm = models.BigIntegerField(blank=True, null=True)
    target_osm = models.BigIntegerField(blank=True, null=True)
    priority = models.FloatField(blank=True, null=True)
    the_geom = models.LineStringField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ways'

analytics/forms.py
#This is to use a certain column names for fields of a form where the user input data

from django.contrib.auth.models import User #user system in the admin # we will tweak the user management system in the admin
from django import forms

from .models import ZIPGPX

# filename column will be used as a field in the file upload form
class FileUploadForm(forms.ModelForm):

    class Meta:
        model = ZIPGPX
        fields = ['filename']

class UserForm(forms.ModelForm): #blueprint for making forms
    password = forms.CharField(widget=forms.PasswordInput) #to hide password/ if empty parenthesis, it returns raw texts

    class Meta: #information about the UserForm class
        model = User
        fields = ['username','email','password'] #specify which information we need out of the original admin

analytics/views.py
# -*- coding: utf-8 -*-
# This contains views which receive a request and response with the processed data to the templates.

from __future__ import unicode_literals
from django.contrib.auth import logout

from django.views.generic import TemplateView
from django.core.serializers import serialize
from django.http import HttpResponse

## user login
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login #autthenticate varifies if the user is registered in db / login attatches a session id wichi is used for browing id without needing to login everytime
from .forms import UserForm, FileUploadForm # import UserForm class

import os

from .models import GPXPoint, GPXFile, SegmentGeoJSON, SegmentCounts, Route, MatchingPoint
from cyclist.settings import BASE_DIR

import zipfile

from django.db.models.signals import pre_save

import json

from django.contrib.gis.utils import LayerMapping

from tcx2gpx import MyHandler, output_set, close_fl
from xml import sax

from matching_to_network import matching_segments
from extract_traveltime import extract_traveltime
from integrate_route_data import integrate_route_data
from segments_to_routes import segments_to_routes
from count_segments import count_segment

from django.contrib.gis.geos import Point

def main(request):
    if not request.user.is_authenticated():
        return render(request, 'analytics/login.html')
    else:
        files = GPXFile.objects.filter(user=request.user)
        return render(request, 'analytics/main.html', {'files': files})

    template_name = 'analytics/mycommute.html'
#This takes a request consisting of username, password, email typed in the form and register the user in the database.
#Afterwards, this makes the user logged in with authentication check and load the main page.
def user_register(request):
        form = UserForm(request.POST or None) # hit the submit button then the typed data is stored in POST, which is passed to the form. The form validate the data

        if form.is_valid():
            user = form.save(commit=False) # creates an object from the form but does not save it to db yet, storing just locally (commit=False)
            #clean normalised data. i.e., format it properlly (ex., unify date format typed differently by users)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)# when you need to change user's password, assign the type password to the user object (update)/should not use use.password = 'bwdjj12' because the original password is asterisk
            user.save() # save the typed user info to db

            #authenticate the user and make him login
            # return User objects if credentials are correct
            user = authenticate(username=username, password=password) # if authenticated, they are stored in user
            if user is not None:
                if user.is_active: #Django admin allows banning or disable a user, so need to check if the user is in those state
                    login(request, user) # if it is not the cases, make the user login
                    return redirect('analytics:main') # then return the home screen
        return render(request, 'analytics/registration_form.html', {'form': form}) # the user is banned to login or fail to be credential, show the black form

#This receives the POST request containing a set of username and password and make the user logged in after authetication.
def login_user(request):
    form = UserForm(request.POST or None)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                files = GPXFile.objects.filter(user=request.user)
                return render(request, 'analytics/main.html', {'files': files})
            else:
                return render(request, 'analytics/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'analytics/login.html', {'error_message': 'Invalid login'})
    return render(request, 'analytics/login.html', {'form': form})

# This makes the user logout when the user click the logout button to make a request to this and load the login page
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'analytics/login.html', context)

#For loading the map page
class MycommuteView(TemplateView):
    template_name = 'analytics/mycommute.html'

#To process data: upzip, save gpx files to the database, map matching, save the map matching results to the database
def process_gpsdata(request):

    point_mapping = {'point': 'POINT',
                     'timestamp': 'time',
                     }
    #Once the form is valid, unzip the submitted zip file
    form = FileUploadForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        #unzip
        zipgpx = form.save(commit=False)
        zipgpx.filename = request.FILES['filename'] #get file name
        zipgpx.user = request.user
        zipgpx.save() # file save and in dababase
        zippath = BASE_DIR + '\\analytics\\routefiles'+'\\' + str(zipgpx.filename)
        zip = zipfile.ZipFile(zippath)
        unzippath = BASE_DIR + '\\analytics\\routefiles\\'+ str(request.user) + '\\' + str(zipgpx.id) # unzip in the user's folder which is created at the same time in the name of the current zipfile id/if the folder or files already exists, it overwrites.
        zip.extractall(unzippath)

        #delete the uploded zipfile
        #zip.close()
        #os.remove(unzippath)

        ##save all the unzipped files into the database
        #If some of the files are .tcxs, they are converted into .gpxs by the tcx2gpx.py
        for (root, dirs, filenames) in os.walk(unzippath):
            for f in filenames:
                if f.endswith(".tcx"):
                    tcx_file = os.path.abspath(os.path.join(os.path.dirname(__file__), 'routefiles/'+str(request.user)+'/'+ str(zipgpx.id) +'/'+ str(f)))
                    output = os.path.abspath(os.path.join(os.path.dirname(__file__), 'routefiles/'+str(request.user)+'/'+ str(zipgpx.id) +'/'+ str(f).replace("tcx","gpx")))
                    output_set(output)
                    handler = MyHandler()
                    sax.parse(tcx_file, handler)
                    close_fl()

        #Read all the gpx files and save them in the database via LayerMapping
        gpxidlist = []
        for (root, dirs, filenames) in os.walk(unzippath):
            for f in filenames:
                if f.endswith(".gpx"):
                    gpx_file = os.path.abspath(os.path.join(os.path.dirname(__file__), 'routefiles/'+str(request.user)+'/'+ str(zipgpx.id) +'/'+ str(f)))
                    lm_tr = LayerMapping(GPXPoint, gpx_file, point_mapping, layer='track_points')
                    gpxfile = GPXFile(user=request.user, filename=str(f))
                    gpxfile.save()
                    gpxidlist.append(gpxfile.pk)
                    #source: https://stackoverflow.com/questions/22324752/django-connect-temporary-pre-save-signal
                    #This is to fill the user field while each row is being populated by layermapping
                    def pre_save_callback(sender, instance, *args, **kwargs):
                        instance.user = request.user # set an instance of the model field and impose value to it which will fill the field this process.
                        instance.gpxfile = gpxfile
                    pre_save.connect(pre_save_callback, sender=GPXPoint)
                    try:
                        lm_tr.save(strict=True)
                    finally:
                        pre_save.disconnect(pre_save_callback, sender=GPXPoint)

        # take the gpxfile objects and gpxpoint objects only for the current user
        user_gpxfiles = GPXFile.objects.filter(user=request.user)
        gpxfiles_of_uploadded = user_gpxfiles.filter(pk__in=gpxidlist) #uploaded gpxfiles
        user_points = GPXPoint.objects.filter(user=request.user)
        #print "took files from db"

        #map matching to OSM network and update gpxfile table with matched segments
        matching_segments_returns = matching_segments(request, gpxfiles_of_uploadded, user_points)
        file_to_segment_list = matching_segments_returns[0]
        file_to_segment_geojson = matching_segments_returns[1]

        #This is for checking matching points
        file_to_coordsliest = matching_segments_returns[2]  # {fileid: [[lat,lng], ..., ], ..., }
        for fileid, latlng_list in file_to_coordsliest.items():
            for latlng in latlng_list:
                point = Point(latlng[1], latlng[0], srid=4326)
                p = MatchingPoint(user=request.user, gpxfile=GPXFile.objects.get(pk=fileid), point=point)
                p.save()
        #for k in file_to_segment_geojson:
            #print "file_to_geojson_k", k

        #count segment and save it to the database
        count_segment(request, SegmentCounts, file_to_segment_list)

        # Grouping files as routes by similarity between segments
        gpxfiles = GPXFile.objects.filter(user=request.user).values('pk','segments')
        gfs = {}
        for i in range(len(gpxfiles)):
            fileid = gpxfiles[i]['pk']
            segments = json.loads(gpxfiles[i]['segments'])
            #print 'pk', type(fileid), fileid
            #print 'jlosd', type(segments), segments
            gfs[fileid] = segments
        route_group_list = segments_to_routes(gfs)

        #This extract travel times of gpxfiles
        traveltime = extract_traveltime(user_points, user_gpxfiles)

analytics/templates/analytics/base.html
<!--This file is to base structure of the web site-->

<!DOCTYPE html>
<html lang="en">

<head>
{% block head %}{% endblock %}

    <meta charset="UTF-8">
    <title>{% block title %}Cyccommute{% endblock %}</title>

    <!-- Loads the path to your static files -->
    {%  load staticfiles %}
    <link rel="stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" /> <!--pull a bootstrap-->
    <link rel="stylesheet" type = "text/css" href="{% static 'style.css' %}" /> <!--load the static files(css)/also tweak the bootstrap so this line is after the bootstrap-->
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" /> <!--pull the Google font-->
    <!--pull jquery and bootstrap javascript files to use functionality like adjustment to the size of the browser-->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <!-- build a navigation bar on the top of the screen using bootstrap-->
</head>
<body>
    <nav class="navbar navbar-inverse"> <!--color: inverse(black)-->
        <div class="container-fluid"> <!--the nav bar at the top of the screen-->

            <!--Header: links back to the home-->
            <div class="navbar-header"> <!--for a home button at the first section of the bar-->
                <!--add menu button which appears when there is not enough space in the screen-->
                <button type ="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> <!--search for id(#topNavBar, named as you like) and make the items inside of the menu-->
                    <span class="icon-bar"></span> <!--add 3 bars for the menu button-->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'analytics:main' %}"> Cyccommute</a> <!--icon to link back to the homepage-->
            </div>

            <!--Manu-->
            <div class="collapse navbar-collapse" id="topNavBar"> <!--make it collapsible on the smaller space/ this button will go inside of the #topNavBar button-->
                <!--Manu on the left end-->
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href = "{% url 'analytics:mycommute' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;My commute
                        </a>
                    </li>
                </ul>

                 <!--Manu on the right end-->
                <ul class="nav navbar-nav navbar-right"> <!--to make sure this is on the right side of the navigation bar-->
                    <!--make add album button-->
                    <li class="active">
                        <a href = "{% url 'analytics:process_gpsdata' %}"> <!--put url to link to the input form according to url in urls.py-->
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add route
                        </a>
                    </li>
                    <!--make logout button-->
                    <li class="active">
                        <a href = "{% url 'analytics:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                        </a>
                    </li>

                    <li class="{% block register_active %}{% endblock %}"><a href="{% url 'analytics:register' %}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

analytics/templates/analytics/base_visitor.html
<!--This file is for the page visitors will see-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cyccommute{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'analytics:main' %}"> Cyccommute</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'analytics:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'analytics:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

analytics/templates/analytics/form-template.html
<!--This is a form template to create a input form which will be used  for the registration.html and upload_files.html-->

{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10"> <!--error message will show up right above the input fields-->
            <span class="text-danger small">{{ field.errors }}</span> <!--error message in tiny size and red(text-danger)-->
        </div>
        <!--label on the right and input box on the left-->
        <label class="control-label col-sm-2">{{ field.label_tag }}</label> <!--2 columns wide/actual text(field.label_tag)-->
        <div class="col-sm-10">{{ field }}</div> <!--input box/ can be dropdown, input, whatever-->
    </div>
{%  endfor %}

<!--add link in base.html-->

analytics/templates/analytics/login.html
<!--This is the login page-->
<!--This block extends from the base_visitor.html-->

{% extends 'analytics/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'analytics:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'analytics:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

analytics/templates/analytics/main.html
<!--This is the main page where the user can see their uploaded files-->
<!--This block extends the base.html-->

{% extends 'analytics/base.html' %} <!--to extend the base.html block part to here-->
{% block title %}Cyccommute{% endblock %}

{% block body %} <!--to place it it in body of base.html-->
    <h3>&nbspUploaded file list</h3>
    {% if files %}
        {% for file in files %}
            <h3>&nbsp{{ file.filename }}</h3>
        {% endfor %}
    {% endif %}

{% endblock %}

analytics/templates/analytics/registration_form.html
<!--This is the sign up page for visitors-->
<!--This block extends the base_visitor.html-->

{% extends 'analytics/base.html' %}
{% block title %}Registration{% endblock %} <!--when this page is open, the title changes to this one/ this is referenced by the title of base.html-->

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    <!--form is placed here-->
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> <!--action: redirect to the same view/enctype:for file upload-->
                        {%  csrf_token %} <!--common security process-->
                        {%  include 'analytics/form-template.html' %} <!--use a form template for input form/ This is not to repeat coding/put label on the right and input fields on the left-->
                        <div class="form-group"> <!--put a submit button-->
                            <div class="col-sm-offset-2 col-sm-10"> <!--not to take up the first 2 areas where labels are placed/bootstrap should take up 10 columns-->
                                <button type="submit" class="btn btn-success">Sumbit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%  endblock %}

analytics/templates/analytics/upload_files.html
<!--This is the file upload page-->
<!--This block extends the base.html-->

{% extends 'analytics/base.html' %}
{% block title %}Add route{% endblock %} <!--when this page is open, the title changes to this one/ this is referenced by the title of base.html-->

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <!--form is placed here-->
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> <!--action: redirect to the same view/enctype:for file upload-->
                        {%  csrf_token %} <!--common security practices-->
                        {%  include 'analytics/form-template.html' %} <!--use a form template for input form/ This is not to repeat coding/put label on the right and input fields on the left-->
                        <div class="form-group"> <!--put a submit button, this is a part of bootstrap-->
                            <div class="col-sm-offset-2 col-sm-10"> <!--not to take up the first 2 areas where labels are placed/bootstrap should take up 10 columns-->
                                <button type="submit" class="btn btn-success">Sumbit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%  endblock %}